Language: ruby
rvm:
  - 2.3.1

script:
  - cp config/database.example.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
addons:
  code_climate:
    repo_token: ENV['CODECLIMATE_REPO_TOKEN']
